apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-externalsecret
  namespace: app
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: app-secretstore
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: SECRET MANAGER
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: SECRET MANAGER
      property: password