apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: app-secretstore
  namespace: app
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: aws-external-seceret